<?php
require_once __DIR__ . '/database.php';
function page_start($title, $area = 1, $showAreas = true) { ?>
<!DOCTYPE html><html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0"><title><?= h($title) ?></title>
<style>
body{margin:0;background:#f3f7f2;color:#23332a;font-family:Arial,sans-serif}.wrap{max-width:1120px;margin:auto;padding:20px}header{background:#176b3a;color:white;box-shadow:0 2px 6px #999}h1{margin:0;font-size:25px}.sub{opacity:.85;margin-top:5px}nav{display:flex;gap:8px;flex-wrap:wrap;margin-top:16px}nav a,.button{border:0;border-radius:7px;padding:10px 14px;text-decoration:none;background:#e8f3eb;color:#145b31;font-weight:bold;cursor:pointer}nav a:hover,.button{background:#1e8548;color:white}.areas{display:flex;gap:8px;flex-wrap:wrap;margin:20px 0}.areas a{padding:9px 15px;border-radius:20px;text-decoration:none;background:#dbe9de;color:#155b31}.areas .selected{background:#176b3a;color:white}.grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(200px,1fr));gap:16px}.card{background:white;padding:18px;border-radius:11px;box-shadow:0 2px 8px #d2d9d3}.metric{font-size:30px;color:#176b3a;font-weight:bold;margin:8px 0}.label{color:#607067;font-size:14px}.status{padding:6px 10px;border-radius:15px;background:#e4f4e8;color:#176b3a;display:inline-block}form.filters{background:white;padding:16px;border-radius:10px;margin:18px 0;display:flex;gap:10px;align-items:end;flex-wrap:wrap;box-shadow:0 2px 8px #d2d9d3}label{display:grid;gap:5px;font-weight:bold}input,select{padding:9px;border:1px solid #b9c8bb;border-radius:6px;font-size:15px}table{width:100%;border-collapse:collapse;background:white;border-radius:10px;overflow:hidden}th,td{padding:11px;text-align:left;border-bottom:1px solid #e3e9e4}th{background:#176b3a;color:white}.notice{padding:13px;background:#fff5d5;border-radius:8px}.ok{padding:13px;background:#e0f3e5;border-radius:8px}@media(max-width:600px){.wrap{padding:14px}h1{font-size:21px}th,td{font-size:12px;padding:8px}}
</style><style>
:root{--purple:#6c3ce9;--pink:#ef3f91;--blue:#168be8;--green:#20a96b}
body{min-height:100vh;background:linear-gradient(135deg,#f5f0ff,#e9faff 48%,#effff3);background-attachment:fixed;color:#26314b;font-family:"Segoe UI",Arial,sans-serif}
body:before,body:after{content:"";position:fixed;border-radius:50%;opacity:.13;z-index:-1;animation:blob 9s ease-in-out infinite}body:before{width:350px;height:350px;background:var(--pink);top:20%;left:-140px}body:after{width:420px;height:420px;background:var(--blue);right:-170px;bottom:-120px;animation-delay:-4s}
header{background:linear-gradient(120deg,#4c2cc4,#087cc8 50%,#09a779);box-shadow:0 8px 30px rgba(51,57,138,.28);position:relative;overflow:hidden}header:after{content:"";position:absolute;inset:0;background:linear-gradient(105deg,transparent 30%,rgba(255,255,255,.17) 50%,transparent 70%);animation:shine 7s infinite}header .wrap{position:relative;z-index:1}h1{font-weight:800;text-shadow:0 2px 10px #273065}
nav a{background:#fff;color:#4d35a5;box-shadow:0 4px 12px #30306b33;transition:.25s}nav a:hover{background:#fff;transform:translateY(-3px);box-shadow:0 8px 18px #25255255}.areas a{background:#fff;color:#6044cb;box-shadow:0 4px 14px #4b39a022;transition:.25s}.areas a:hover{transform:translateY(-3px);color:var(--pink)}.areas .selected{background:linear-gradient(135deg,var(--purple),var(--pink));color:#fff;box-shadow:0 7px 18px #c9348f55}h2,h3{color:#35257a}
.card,form.filters,table{border:1px solid #ffffffdd;box-shadow:0 10px 30px #41367d22}.card{position:relative;overflow:hidden;border-radius:18px;padding:22px;transition:.3s;animation:cardIn .55s both}.card:nth-child(2){animation-delay:.08s}.card:nth-child(3){animation-delay:.16s}.card:nth-child(4){animation-delay:.24s}.card:hover{transform:translateY(-8px) scale(1.02);box-shadow:0 18px 38px #41367d38}
.sensor-icon{font-size:30px;position:absolute;right:18px;top:15px;animation:pulse 2.4s ease-in-out infinite}.temperature-card{background:linear-gradient(145deg,#fff,#fff0e6);border-top:5px solid #ff7135}.humidity-card{background:linear-gradient(145deg,#fff,#e8f6ff);border-top:5px solid #248bea}.soil-card{background:linear-gradient(145deg,#fff,#edffe8);border-top:5px solid #4caf48}.rain-card{background:linear-gradient(145deg,#fff,#f0ecff);border-top:5px solid #7e55df}.temperature-card .metric{color:#ed592c}.humidity-card .metric{color:#147ed1}.soil-card .metric{color:#36943b}.rain-card .metric{color:#7045cb}
.progress{height:9px;background:#55557c18;border-radius:10px;overflow:hidden;margin:10px 0}.progress span{display:block;height:100%;border-radius:10px;background:linear-gradient(90deg,#12bfc7,var(--purple),var(--pink));animation:grow 1.1s ease-out}.button{background:linear-gradient(135deg,var(--purple),var(--pink));color:#fff;box-shadow:0 5px 14px #8439bd44;transition:.25s}.button:hover{transform:translateY(-2px)}
form.filters{border-radius:16px;background:#ffffffdf}input,select{border:2px solid #ddd5fa;background:#fff;transition:.25s}input:focus,select:focus{outline:0;border-color:var(--purple);box-shadow:0 0 0 4px #6c3ce922}table{border-radius:16px}th{background:linear-gradient(120deg,#5936c8,#188acb)}tbody tr{transition:.2s}tbody tr:hover{background:#f2efff}.status{background:linear-gradient(135deg,#e4fff1,#e8f5ff);color:#167354}.notice{background:linear-gradient(135deg,#fff4cf,#ffe8ef);border-left:5px solid #f59b23}.ok{background:linear-gradient(135deg,#dffff0,#e6f3ff);border-left:5px solid var(--green)}
@keyframes cardIn{from{opacity:0;transform:translateY(22px)}to{opacity:1;transform:none}}@keyframes grow{from{width:0}}@keyframes pulse{50%{transform:scale(1.13) rotate(4deg)}}@keyframes shine{0%,65%{transform:translateX(-100%)}85%,100%{transform:translateX(100%)}}@keyframes blob{50%{transform:translate(35px,-25px) scale(1.08)}}@media(prefers-reduced-motion:reduce){*,*:before,*:after{animation:none!important;transition:none!important}}
</style><style>
body{background-image:linear-gradient(135deg,rgba(240,248,255,.48),rgba(226,255,242,.34)),url('images/dashboard.jpg');background-size:cover;background-position:center;background-repeat:no-repeat;background-attachment:fixed}
body:before,body:after{display:none}header{text-align:center;background:linear-gradient(110deg,rgba(66,39,188,.94),rgba(4,133,190,.92),rgba(0,151,112,.92));backdrop-filter:blur(10px)}header .wrap{display:flex;flex-direction:column;align-items:center}header h1{font-size:clamp(25px,3vw,36px);letter-spacing:-.4px}header .sub{font-size:15px;margin-top:8px}nav{justify-content:center;margin-top:20px}.areas{justify-content:center;margin:28px 0 24px}main.wrap>h2{text-align:center;font-size:clamp(25px,3vw,34px);margin:10px 0 28px}main.wrap>p.status{display:table;margin:0 auto 22px}.sensor-grid{text-align:center}.sensor-grid .card{display:flex;min-height:210px;flex-direction:column;align-items:center;justify-content:center}.sensor-grid .sensor-icon{position:static;margin-bottom:9px;font-size:34px}.sensor-grid .metric{font-size:36px}.sensor-grid .progress{width:100%;max-width:220px}.sensor-grid+.button,.sensor-grid~p{text-align:center}main.wrap>p:last-child{text-align:center}.sensor-grid~p .button{display:inline-block;padding:13px 22px;border-radius:12px}
form.filters{justify-content:center}main.wrap>h3{text-align:center}table th,table td{text-align:center}table td:first-child,table th:first-child{text-align:left}
header h1{font-size:clamp(36px,3.5vw,50px);line-height:1.1}header h1 .brand-line{display:inline}header h1 .brand-line:last-child{font-size:1em;color:#d8ffbe;margin:0}main.wrap>h2{display:table;margin-left:auto;margin-right:auto;padding:10px 22px;border-radius:15px;background:rgba(255,255,255,.76);backdrop-filter:blur(10px);box-shadow:0 8px 25px rgba(34,38,91,.13)}
main.wrap{width:min(1120px,calc(100% - 32px));padding:28px 0 60px}.areas{margin-top:0}main.wrap>h2{margin-top:0;margin-bottom:28px;text-align:center}main.wrap>.notice{max-width:1120px;margin:0 auto 16px;text-align:center;line-height:1.55;box-shadow:0 8px 24px rgba(40,40,80,.12)}main.wrap>.status{margin-top:0!important;margin-bottom:22px!important}form.filters{width:100%;min-height:96px;margin:18px auto;padding:20px 24px;justify-content:center;align-items:end;gap:12px}form.filters>div{text-align:left}form.filters label{text-align:left}form.filters .button{min-height:39px}main.wrap>table{margin:18px auto 0}main.wrap>h3{display:table;margin:20px auto 12px;padding:7px 16px;border-radius:10px;background:rgba(255,255,255,.76);backdrop-filter:blur(8px)}table th,table td{vertical-align:middle}table th{height:46px}table td{height:43px}.ok{max-width:1120px;margin:14px auto;text-align:center}
.reading-selection{width:100%;margin:0 auto}.reading-selection table{margin:0}.reading-selection input[type=radio]{width:20px;height:20px;accent-color:#7a3de2;cursor:pointer}.selectable-row{cursor:pointer}.selectable-row:has(input:checked){background:#eee8ff;box-shadow:inset 5px 0 #7a3de2}.selection-actions{display:flex;align-items:center;justify-content:center;gap:22px;margin:16px 0;padding:18px 22px;border-radius:14px;background:rgba(255,255,255,.9);box-shadow:0 10px 30px rgba(65,54,125,.15);text-align:left}
@media(max-width:700px){body{background-attachment:scroll;background-position:center}header .wrap{padding:22px 15px}header h1{font-size:27px;line-height:1.12}.sub{font-size:12px!important}nav{width:100%;display:grid;grid-template-columns:1fr 1fr;gap:9px}nav a{padding:11px 8px;font-size:13px}main.wrap{width:min(calc(100% - 24px),1120px);padding:20px 0 40px}.areas{gap:7px;margin:0 0 20px}.areas a{padding:9px 12px;font-size:13px}main.wrap>h2{font-size:22px;margin-bottom:20px;padding:9px 14px}.sensor-grid{grid-template-columns:1fr}.sensor-grid .card{min-height:180px}.sensor-grid .metric{font-size:34px}form.filters{min-height:0;padding:17px;align-items:stretch}form.filters>div{text-align:center}form.filters label,form.filters input,form.filters select,form.filters .button{width:100%}main.wrap>.notice{font-size:13px;padding:12px}table{display:block;overflow-x:auto;white-space:nowrap}}
@media(max-width:700px){.selection-actions{flex-direction:column;text-align:center;gap:12px}.selection-actions .button{width:100%}}
</style></head><body><header><div class="wrap"><h1><span class="brand-line">Agri Shield</span> <span class="brand-line">&amp; Weather Prediction</span></h1><div class="sub">ESP32 Sensor Monitoring • Sensor History • 4 Areas</div><nav><a href="app.php?area=<?= (int)$area ?>">Live Dashboard</a><a href="history.php?area=<?= (int)$area ?>">History &amp; Save</a><a href="prediction.php?area=<?= (int)$area ?>">Prediction</a><a href="drought.php">Drought Predictor</a><a href="satellite.php">Satellite Report</a><a href="logout.php">Logout</a></nav></div></header><main class="wrap"><?php if ($showAreas): ?><div class="areas"><?php for ($i=1;$i<=4;$i++): ?><a class="<?= $area===$i?'selected':'' ?>" href="<?= h(basename($_SERVER['PHP_SELF'])) ?>?area=<?= $i ?>">Area <?= $i ?></a><?php endfor; ?></div><?php endif; ?>
<?php }
function page_end() { echo '</main><script>window.addEventListener("load",function(){window.scrollTo(0,0);});</script></body></html>'; }
?>
